Created entities for BE
ernestas20111/FlowerEshop pull request #5
Opened 2022-04-11 15:26 UTC by JustasVit

Created main entities for BE.  Furthermore, provided relational diagram of our current database. 
![Diagram](https://user-images.githubusercontent.com/71339306/162773346-bb8d2f4f-22c8-45a4-a67e-20fd55906a0d.png)

I would highly appreciate your feedback @ernestas20111 @viliusmac @JuozasVainauskas @AivarasRinkevicius

2022-04-12 13:01 UTC, AivarasRinkevicius commented
We could have one shopping cart with all the products in it (saving id multiple times should not be a problem for the performance). I don't see a use case for cart **createdAt** and **modifiedAt**. Maybe I misunderstand something.

2022-04-12 13:11 UTC, JustasVit commented
> We could have one shopping cart with all the products in it (saving id multiple times should not be a problem for the performance). I don't see a use case for cart **createdAt** and **modifiedAt**. Maybe I misunderstand something.

Right now there is one to one relationship between user and shopping cart. CreatedAt and modifiedAt are just timestamps, I thought that maybe it would be relevant, if we are going to save shopping carts for a certain period of time and then discard them, if a user is inactive (maybe he wants to complete his order after a couple of days, but not right now).

2022-04-12 13:12 UTC, viliusmac commented
UserOrder, OrderDetails and PurchasedProduction should be one table to reduce complexity. If an order is executed there should just be another boolean value that would say "Order executed" -> True, "Order pending/Order dismised" -> False. I think best solution is to have table "Order" with timestamp, payment details and a refference to a table "OrderedItem" which would have ItemId and Quantity. Something like that.

2022-04-12 13:18 UTC, JustasVit commented
> Order status cannot be an integer. It's either a boolean or a reference to another table with "Enum" values (if we are tracking all steps > 2)

It was automatically generated by hibernate, so I guess it has it's own interpretation of integer under the hood.

2022-04-12 13:27 UTC, AivarasRinkevicius requested changes

2022-04-12 13:27 UTC, AivarasRinkevicius commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
We don't need to catch exceptions here because we have a global error (exception) handler (you should see it in the error folder).  You can simply **throw  new EntityNotFoundException** and global error handler will send the appropriate response.

2022-04-12 13:27 UTC, AivarasRinkevicius commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +        } catch (Exception e){
Same here with the error handling and everywhere else, as stated in the comment above.

2022-04-12 13:27 UTC, AivarasRinkevicius commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/purchasedProductItem/controller/PurchasedProductItemController.java
> +    public ResponseEntity<PurchasedProductItem> updatePurchasedProductItem(@PathVariable("id") Long ID, @RequestBody PurchasedProductItem purchasedproductItem) {
I think you did a bit too much at this point. For example, we don't know if we need to update all fields or if we could use PATCH and update only one field. We will refactor controllers when we know what we need. I think we could leave it as it is now.

2022-04-12 13:59 UTC, JustasVit commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +        } catch (Exception e){
Fixed.

2022-04-12 14:00 UTC, JustasVit commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
Fixed.

2022-04-12 19:30 UTC, JustasVit commented
Recently edited the relational diagram according to the given feedback
![Untitled_Document_4](https://user-images.githubusercontent.com/71339306/163039072-714867b3-2232-4504-822a-9112c14e72b5.png)

2022-04-12 19:31 UTC, JuozasVainauskas approved these changes

2022-04-12 19:35 UTC, AivarasRinkevicius approved these changes

2022-04-13 11:46 UTC, ernestas20111 commented
![image](https://user-images.githubusercontent.com/19888527/163173171-6666c956-b6bd-457d-84ab-63aaf874482d.png)
@JustasVit Shouldn't userID exist as foreign key in ShoppingCart as well?

2022-04-13 11:47 UTC, ernestas20111 requested changes
Address the comment

2022-04-13 11:52 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/user/entity/UserStatus.java
> +    CUSTOMER,ADMIN
Write like this: 
```
public enum UserStatus {
    CUSTOMER,
    ADMIN
}
```
It will look cleaner

2022-04-13 11:53 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/order/entity/OrderStatus.java
> +    NOT_DELIVERED,IN_PROGRESS,RETURNED,DELIVERED
Write like this:
```
public enum OrderStatus {
    NOT_DELIVERED,
    IN_PROGRESS,
    RETURNED,
    DELIVERED
}
```
It will look cleaner.

2022-04-13 11:54 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/review/entity/ReviewType.java
> +    COMPLAINT, RECOMMENDATION
Write like this:
```
public enum ReviewType {
    COMPLAINT,
    RECOMMENDATION
}
```
It will look cleaner.

2022-04-13 11:59 UTC, JustasVit commented
> ![image](https://user-images.githubusercontent.com/19888527/163173306-4a4bd7ac-7450-4a47-84ce-468c8dff8256.png)
> @JustasVit Shouldn't userID exist as foreign key in ShoppingCart as well?

Because the relation is one to one, cartID = userID

2022-04-13 12:05 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/service/CategoryService.java
>  public interface CategoryService {
To be honest - all interfaces like `CategoryService`, `ProductService`, `PurchasedProductItemService`, `UserService` are just CRUDService interface. So instead of different naming which is basically the same thing, create generic CRUDInterface like so
```
public interface CRUDService<E, T> {
    List<E> findAll();
    E findById(T id);
    void deleteById(T id);
    void deleteAll();
    void save(E entity);
    void saveAll(List<E> entities);
}
```

2022-04-13 12:08 UTC, JustasVit commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/service/CategoryService.java
>  public interface CategoryService {
I talked about it with others and right now these services are just as examples, but yes, you have a good point.

2022-04-13 12:11 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/service/CategoryService.java
>  public interface CategoryService {
I would suggest addressing this in current pr since this is not a big change to do now, but in the future with more entities and maybe more specifics it could be more difficult to refactor in my opinion.

2022-04-13 12:23 UTC, ernestas20111 commented
> > ![image](https://user-images.githubusercontent.com/19888527/163173306-4a4bd7ac-7450-4a47-84ce-468c8dff8256.png)
> > @JustasVit Shouldn't userID exist as foreign key in ShoppingCart as well?
> 
> Because the relation is one to one, cartID = userID

Well, If I recall correctly in one to one and many to many relationships, one entity must be the owning side, so it would be good to include that foreign key to one of those tables to see which entity is the owning side and which not.
Example of one to one relationship:
![image](https://user-images.githubusercontent.com/19888527/163178780-61d306fb-9014-46d4-8fd2-65d93161650b.png)

2022-04-13 14:29 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/product/controller/ProductController.java
> +        Product returnedProduct = productService.findProductById(ID);
Same comment applies as in https://github.com/ernestas20111/FlowerEshop/pull/5/files#r849549625

2022-04-13 14:30 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/purchasedProduct/controller/PurchasedProductController.java
> +        if (returnedPurchasedProduct != null) {
Same comment applies as in https://github.com/ernestas20111/FlowerEshop/pull/5/files#r849549625

2022-04-13 14:30 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/user/controller/UserController.java
> +        if (returnedUser != null) {
Same comment applies as in https://github.com/ernestas20111/FlowerEshop/pull/5/files#r849549625

2022-04-13 16:27 UTC, JustasVit commented
> > > ![image](https://user-images.githubusercontent.com/19888527/163173306-4a4bd7ac-7450-4a47-84ce-468c8dff8256.png)
> > > @JustasVit Shouldn't userID exist as foreign key in ShoppingCart as well?
> > 
> > 
> > Because the relation is one to one, cartID = userID
> 
> Well, If I recall correctly in one to one and many to many relationships, one entity must be the owning side, so it would be good to include that foreign key to one of those tables to see which entity is the owning side and which not. Example of one to one relationship: ![image](https://user-images.githubusercontent.com/19888527/163178780-61d306fb-9014-46d4-8fd2-65d93161650b.png)

As you can see, userID in shopping cart is primary and foreign key at the same time, so it is possible to see the owning side in the diagram.

2022-04-13 16:32 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/CRUDservice.java
> +public interface CRUDservice<E>{
All is good, except I think this could be called CrudService since we already have CrudRepository named in that manner.
![image](https://user-images.githubusercontent.com/19888527/163227667-3e8532b9-df98-47ba-8852-5b3718d4a75e.png)

2022-04-13 16:34 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/product/service/ProductCRUDServiceImpl.java
> +public class ProductCRUDServiceImpl implements CRUDservice<Product> {
Same applies for other services as well

2022-04-13 16:40 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +    }
Would be nicer if else and if were switched places.
Instead of
```
if (categories.isEmpty()) {
      return new ResponseEntity < > (HttpStatus.NO_CONTENT);
} else return new ResponseEntity < > (categories, HttpStatus.OK);
```
could be
```
if (categories.isEmpty()) {
      return new ResponseEntity < > (categories, HttpStatus.OK);
} else return new ResponseEntity < > (HttpStatus.NO_CONTENT);
```

2022-04-13 16:41 UTC, ernestas20111 requested changes
A few improvements could be made

2022-04-13 16:41 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +    }
Same for other controllers as well

2022-04-13 16:42 UTC, ernestas20111 commented on flower-e-shop-backend/src/main/java/com/wenomechainsama/flowerEshop/category/controller/CategoryController.java
> +    }
Same for other controllers as well

2022-04-13 17:27 UTC, ernestas20111 approved these changes

2022-04-13 17:30 UTC, merged